# Site settings
title: Olmec Dev
description: 'Thinking space for Sitecore development'
url: 'https://olmecdev.com'
baseurl: ''
google_analytics: 'UA-137537427-1'
disqus_shortname: 'olmec-dev'

author:
  name: 'Olivier McNicoll'
  email: omcnicoll@gmail.com
  github_username:  omcnicoll
  linkedin_username:  olivier-mcnicoll-62729290

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
